api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('status/', views.get_server_status, name='status'),
    path('errors/', views.get_errors, name='errors'),
    path('error/<int:code>/', views.get_error_from_code, name='error_by_code'),
    path('error/', views.create_error, name='create_error'),
    path('object/<int:id>/', views.object_update, name='object_update'),
]

games/urls.py
from django.urls import path
from . import views

app_name = 'games'
urlpatterns = [
    path('list/', views.game_list, name='list'),
    path('create/', views.create_game, name='create'),
    path('<int:game_id>/', views.game_detail, name='detail'),
    path('close/', views.close_game, name='close')
]

tic_tac_toe/urls.py
from django.contrib import admin
from django.urls import path, include
from tic_tac_toe import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', views.homepage, name='homepage'),
    path('games/', include('games.urls', namespace='games')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls')),
    path('random_jokes/', include('random_jokes_api.urls'))
]

games/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):
    room_name = models.CharField(max_length=50, unique = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_games')
    player2 = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='joined_games')
    board = models.CharField(max_length=9, default='_'*9)
    active_player = models.IntegerField(default=1)
    STATE_CHOICES = [
        ('active', 'Active'),
        ('won', 'Won'),
        ('tie', 'Tie')
    ]
    state = models.CharField(max_length=10, choices=STATE_CHOICES, default='active')
    winner = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='won_games')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.room_name} ({self.state})"

games/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Game
import re

# Lista de juegos
@login_required
def game_list(request):
    games = Game.objects.all()
    return render(request, 'games/list.html', {'games': games})

# Crear la partida
@login_required
def create_game(request):
    if request.method == 'POST':
        # comrpobar q el nombre de la sala es válido (por tema ws)
        room_name = request.POST.get('room_name', '').strip()
        room_name = room_name.lower()
        room_name = room_name.replace(" ", "-")
        room_name = re.sub(r"[^a-z0-9-_\.]", "", room_name)
        
        # no has introducido nombre
        if not room_name:
            return redirect('games:create')
        
        # ya existe una partida con ese nombre
        if Game.objects.filter(room_name=room_name).exists():
            return redirect('games:create')
        
        # crea la partida
        game = Game.objects.create(
            room_name=room_name,
            owner=request.user,
            board='_' * 9,
            active_player=1,
            state='active'
        )
        return redirect('games:list')
    
    return render(request, 'games/create.html')

# Partida en detalle
@login_required
def game_detail(request, game_id):

    game = Game.objects.get(id=game_id)
    
    # el q ha entrado es el q la ha creado?
    user_is_owner = (request.user == game.owner)

    # convierte el tablero en una lista para mostrarlo más
    # fácilmente en la plantilla.
    board = list(game.board)

    return render(request, 'games/detail.html', {
        'game': game,
        'board': board,
        'user_is_owner': user_is_owner
    })

# Decidir ganador
def check_winner(board):
    # combinaciones ganadoras
    combos = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]
    
    # para cada trío de posiciones que forme una línea ganadora
    for a, b, c in combos:
        # la casilla no está vacía y las tres casillas tienen el mismo valor
        if board[a] != '_' and board[a] == board[b] == board[c]:
            # devuelve el símbolo ganador ('X' o 'O')
            return board[a]
        
    # no quedan huecos: empate
    if '_' not in board:
        return 'Tie'
    
    # no hay ganador: nada
    return None

# Eliminar la partida
@login_required
def close_game(request):
    if request.method == 'POST':
        game = Game.objects.get(id=request.POST.get('name'))
        
        # elimina la partida con su id (que se envía desde el form)
        game.delete()
        return redirect('games:list')
    
    return redirect('games:list')

games/templates/games/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Create a game
{% endblock %}
{% block content %}

<div class="max-w-[30%] mx-auto mt-[150px]">
    <section class="flex flex-col text-center bg-gray-800 p-[15px] rounded-[10px] shadow-md font-semibold">
        <h1 class="text-[30px] text-white shadow-md py-[10px]">Create a game</h1>
        <form method='post'>
            {% csrf_token %}

            <div>
                <label class="block mb-[5px] mt-[25px] text-white font-[25px]">Room name:</label>
                <input class="mb-[10px] p-2 rounded-[8px] bg-gray-900 text-white focus:outline-none" type="text" name="room_name" required>
            </div>

            <button type="submit"
                class="w-full bg-gray-950 text-white rounded-[8px] py-[10px] mt-[20px] cursor-pointer">Create room</button>
        </form>
    </section>
</div>

{% endblock %}

games/templates/games/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ game.room_name }}
{% endblock %}

{% block content %}
<div class="max-w-[40%] mx-auto bg-gray-800 py-[20px] rounded-[10px] mt-[70px] mb-[70px]">
    <section class="max-w-[90%] mx-auto text-white text-center">
        <h1 class="text-[40px] font-semibold bg-gray-950 text-center py-[5px] rounded-[10px] mb-[40px]">
            {{ game.room_name }}</h1>
        <p id="turn" class="mb-[30px]">Current player: </p>

        <!-- CONTENEDOR DEL TABLERO  -->
        <div id="board_container" class="grid grid-cols-3 gap-[8px] mx-auto place-items-center
            w-[260px] h-[260px]">
        </div>
    </section>
</div>

<script>
// VARIABLES INICIALES
const roomName = "{{ game.room_name }}";
const userId = "{{ request.user.id }}";
let board = "{{ game.board }}".split("");
let state = "{{ game.state }}";   // estado inicial
const csrfToken = "{{ csrf_token }}"; // token para el form dinámico
let activePlayer = "{{ game.active_player }}";

// FUNCION Q DIBUJA EL TABLERO
function renderBoard() {
    const container = document.getElementById("board_container");
    container.innerHTML = "";

    for (let i = 0; i < 9; i++) {
        const empty = board[i] === "_";
        // crear element dependiendo de si está libre u ocupado
        const cell = document.createElement(empty ? "button" : "div");

        // clases comunes
        if (empty) {
            // si la partida está activa, el botón es clickeable y con hover
            if (state === "active") {
                cell.className = "h-[80px] w-[80px] bg-gray-900 hover:bg-gray-700 text-[30px] rounded-[8px]";
                cell.onclick = () => playMove(i);
            } else {
                // partida terminada, mostrar casilla inactiva
                cell.className = "h-[80px] w-[80px] border border-gray-600 rounded-[8px]";
            }
        } else {
            cell.className = "h-[80px] w-[80px] border border-gray-600 rounded-[8px] flex items-center justify-center text-[35px] font-bold text-gray-200";
            cell.innerText = board[i];
        }

        container.appendChild(cell);
    }
}

// MUESTRA RESULTADO
function updateResultUI(data) {
    const section = document.querySelector("section");
    let resultDiv = document.getElementById("result_div");

    // creamos el contenedor si no existe
    if (!resultDiv) {
        resultDiv = document.createElement("div");
        resultDiv.id = "result_div";
        resultDiv.className = "mt-[30px]";
        section.appendChild(resultDiv);
    }

    if (data.state === "won") {
        resultDiv.innerHTML = `
            <p class="text-[22px] font-semibold text-green-400">
                🏆 Winner: ${data.winner_username || "Jugador"}
            </p>
        `;
    } else if (data.state === "tie") {
        resultDiv.innerHTML = `
            <p class="text-[22px] font-semibold text-yellow-400">
                🤝 Tie
            </p>
        `;
    } else {
        // si vuelve a active por alguna razón, lo limpiamos
        resultDiv.innerHTML = "";
    }
}

// AÑADIR BOTON DE CERRAR
function ensureCloseButton(ownerId, gameId) {
    // solo el owner puede ver el boton
    if (ownerId !== userId) return;

    let closeForm = document.getElementById("close_room_form");
    if (closeForm) return; // ya existe

    const section = document.querySelector("section");

    closeForm = document.createElement("form");
    closeForm.id = "close_room_form";
    closeForm.method = "post";
    closeForm.action = "{% url 'games:close' %}";
    closeForm.className = "mt-[20px]";

    // usamos token CSRF que hemos puesto en csrfToken
    closeForm.innerHTML = `
        <input type="hidden" name="csrfmiddlewaretoken" value="${csrfToken}">
        <input type="hidden" name="name" value="${ game.id }">
        <button type="submit" class="bg-red-900 text-[20px] py-[10px] px-[40px] rounded-[8px] cursor-pointer">
            Close room
        </button>
    `;

    section.appendChild(closeForm);
}

// ACTUALIZAR TURNO
function updateTurnUI(data) {
    const el = document.getElementById("turn");
    if (!el) return;

    // Si partida terminada → limpiar
    if (data.state !== "active") {
        el.innerText = "";
        return;
    }

    // Si aún no hay jugador 2
    if (!data.player2_id) {
        el.innerText = "Waiting for player 2...";
        return;
    }

    // Mostrar nombre si viene en el payload
    if (data.turn_username) {
        el.innerText = `Current player: ${data.turn_username}`;
        return;
    }

    el.innerText = "";
}

// WEBSOCKET
const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
const wsUrl = protocol + "//" + window.location.host + "/ws/games/" + roomName + "/";
const socket = new WebSocket(wsUrl);

socket.onopen = function () {
    console.log("Connected to game socket", wsUrl);
    socket.send(JSON.stringify({ action: "join", user_id: userId }));
};

socket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    console.log("DATA FROM SERVER:", data);
    if (!data) return;

    // actualizamos estado y tablero locales
    if (typeof data.board === "string") board = data.board.split("");
    if (data.state) state = data.state;
    if (data.active_player) activePlayer = data.active_player;


    // render y actualizar UI de resultado/botón/turno
    renderBoard();
    updateTurnUI(data);
    if (data.state && data.state !== "active") {
        updateResultUI(data);
        ensureCloseButton(data.owner_id, data.id);
    }
};

socket.onclose = function (e) {
    console.log("Socket closed", e); 
};

socket.onerror = function (err) {
    console.error("Socket error", err); 
};

// ENVIAR JUGADA
function playMove(index) {
    // si la partida ya ha terminado, no enviar
    if (state !== "active") return;

    socket.send(JSON.stringify({
        action: "move",
        user_id: userId,
        index: index
    }));
}

// RENDERIZADO INICIAL
renderBoard();
</script>

{% endblock %}

games/templates/games/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
List of games
{% endblock %}

{% block content %}
<section class="mx-[40px] mt-[20px] text-center text-white">
    <h1 class="text-[40px] font-semibold bg-gray-950 text-center py-[10px] rounded-[10px] mb-[20px]">List of games</h1>
    <a class="bg-gray-950 rounded-sm text-[20px] py-[10px] px-[40px]" href="{% url 'games:create' %}">➕ New
        game</a>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-[40px] mt-[40px] mb-[40px]">
        {% for game in games %}
        <div
            class="flex flex-col text-left bg-gray-800 text-center py-[10px] px-[20px] rounded-[10px] shadow-md">
            <p class="text-[25px] font-semibold">{{ game.room_name }}</p>
            <p class="text-[18px] text-gray-300">Creator: {{ game.owner.username }}</p>
            <p class="text-[18px] text-gray-300">State: {{ game.state }}</p>

            <form action="{% url 'games:detail' game.id %}" method="post" class="mt-[15px]">
                {% csrf_token %}
                <input type="hidden" name="name" value="{{ game.id }}">
                <button type="submit" class="bg-gray-950 rounded-sm text-[20px] py-[10px] px-[20px] w-full cursor-pointer">
                    {% if request.user == game.owner %}🎮 Play{% else %}👀 View{% endif %}
                </button>
            </form>

            {% if request.user == game.owner and game.state != 'active' %}
            <form action="{% url 'games:close' %}" method="post" class="mt-[10px]">
                {% csrf_token %}
                <input type="hidden" name="name" value="{{ game.id }}">
                <button type="submit" class="bg-red-900 rounded-sm text-[18px] py-[8px] px-[20px] w-full cursor-pointer">Close room</button>
            </form>
            {% endif %}
        </div>
        {% empty %}
        <p class="text-[20px] font-semibold mt-[50px] col-span-full">No games yet.</p>
        {% endfor %}
    </div>
</section>
{% endblock %}